name: Feature request
description: Suggest an idea
labels: ["feat", "pending"]
title: "[FR]: "
body:
  - type: markdown
    attributes:
      value: |
        Before submitting this request, please search existing issues and make sure it's unique.
        If you ignore this text, and create this one, you will be permanently banned from
        interacting with the entire organization.

        Please do not use AI for writing your request's description, no one wishes
        to read that and thus your request will be closed.

        If your request is for a feature that would apply to all platforms, and
        not just Windows, please submit it to the generic "helium" repo instead.
  - type: input
    id: description
    attributes:
      label: Description
      description: A clear and concise description (in one line) of what your suggestion is
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Who's implementing?
      options:
        - label: I'm willing to implement this feature myself
  - type: textarea
    id: prob
    attributes:
      label: The problem
      description: Please describe the problem you are solving or new feature you're suggesting
      placeholder: I'm always frustrated when [...] happens
    validations:
      required: true
  - type: textarea
    id: sol
    attributes:
      label: Possible solutions
      description: Please describe possible solution(-s) to your problem
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the feature request here
