name: Build and release binaries
on:
  workflow_dispatch:
    inputs:
      runner:
        required: false
        description: 'Runner image name'
        default: 'windows-2025'
      do-release:
        required: false
        type: boolean
        description: 'Create a release after build is done'
        default: false

permissions:
  contents: read

jobs:
  build:
    name: Build ${{ matrix.arch }}
    strategy:
      matrix:
        arch: [x86_64, arm64]
      fail-fast: false
    uses: ./.github/workflows/build-steps.yml
    secrets: inherit
    with:
      arch: ${{ matrix.arch }}
      runs-on: ${{ inputs.runner }}

  publish-release:
    needs: build
    if: ${{ inputs.do-release }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          fetch-tags: true
      - uses: ./.github/actions/release
        with:
          version: ${{ needs.build.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
